proxy:
	@export HTTP_PROXY="http://172.20.20.104:8080" && \
  export HTTPS_PROXY="http://172.20.20.104:8080" && \
	export http_proxy="http://172.20.20.104:8080" && \
  export https_proxy="http://172.20.20.104:8080"

ssh:
	@echo "やってるぜ" && \
	/usr/sbin/sshd -D
